### ISSUE TITLE
 flutter_workspace.py fails when looking for the freetype2-dev dependency

### ISSUE THREAD

**Issue by JoshDavisChem** [meta-flutter/workspace-automation#11]
apt install calls at line 46 and 58  in [config/flutter-engine.json](https://github.com/meta-flutter/workspace-automation/blob/main/configs/flutter-engine.json) should probably replace "freetype2-dev" with "libfreetype-dev" or "libfreetype6-dev". I am not sure which one should be used or if they are the same library with different names for legacy reasons. 
Replacing "freetype2-dev" with "libfreetype-dev" worked for me.

~~~
apt search libfreetype
Sorting... Done
Full Text Search... Done
libcoin80c/focal 4.0.0+ds-1build1 amd64
  high-level 3D graphics kit implementing the Open Inventor API

libfreetype-dev/focal-updates,focal-security,now 2.10.1-2ubuntu0.3 amd64 [installed]
  FreeType 2 font engine, development files

libfreetype6/focal-updates,focal-security,now 2.10.1-2ubuntu0.3 amd64 [installed,automatic]
  FreeType 2 font engine, shared library files

libfreetype6-dev/focal-updates,focal-security,now 2.10.1-2ubuntu0.3 amd64 [installed]
  FreeType 2 font engine, development files (transitional package)

libgd-perl/focal,now 2.71-2build1 amd64 [installed,automatic]
  Perl module wrapper for libgd
~~~

**Comment by JoshDavisChem** [comment]
I am installing on Ubuntu 20.04 by the way

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/workspace-automation/pull/12
