### ISSUE TITLE
Failing to Download Engine artifact 

### ISSUE THREAD

**Issue by bernardcraddock** [meta-flutter/workspace-automation#24]
@jwinarske - Sorry don't mean to hassle you, 

due to unforeseen circumstances I had to trash/rebuild my fedora env, and now running flutter_workspace.py "no matter what options" I pass it's failing to download the engine Artifacts.
I've never had this issue before so don't know if it's yours or mine if yours could it be the Engine Version:
if mine can you advise? 
 
wa-vm > ./flutter_workspace.py --flutter-version=3.16.5 --fetch-engine 
********************************************************************************************
** Setting up Flutter Workspace in: /home/parallels/Documents/GitHub/workspace-automation **
********************************************************************************************
.../...
*******************************
** Fetching Engine Artifacts **
*******************************
Engine Version: 3f3e560236539b7e2702f5ac790b2a4691b32d49
Working Directory: /home/parallels/Documents/GitHub/workspace-automation/.config/flutter_workspace/flutter-engine
*********************************
** Downloading Engine artifact **
*********************************
** Downloading linux-x64-embedder.zip via https://storage.googleapis.com/flutter_infra_release/flutter/3f3e560236539b7e2702f5ac790b2a4691b32d49/linux-x64/linux-x64-embedder
**************************
** Download Status: 404 **
**************************
***********************************************
** Failed to download linux-x64-embedder.zip **
***********************************************
***********************************
** Engine artifact not available **
***********************************

wa-vm > flutter doctor -v
[!] Flutter (Channel [user-branch], 3.16.5, on Fedora Linux 38 (Workstation Edition) 6.6.9-100.fc38.x86_64, locale en_US.UTF-8)
    ! Flutter version 3.16.5 on channel [user-branch] at /home/parallels/Documents/GitHub/workspace-automation/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (2 available)
    • Linux (desktop)            • linux              • linux-x64 • Fedora Linux 38 (Workstation Edition) 6.6.9-100.fc38.x86_64
    • Toyota homescreen (mobile) • desktop-homescreen • linux-x64 • homescreen x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by bernardcraddock** [comment]
its workspace-automation main branch

**Comment by bernardcraddock** [comment]
@jwinarske

flutter_workspace.py -b main worked fine after manually doing following.

1. download linux-x64-embedder.zip
curl -O https://storage.googleapis.com/flutter_infra_release/flutter/3f3e560236539b7e2702f5ac790b2a4691b32d49/linux-x64/linux-x64-embedder

2. update flutter-engine load back to true
gitd configs/flutter-engine.json
diff --git a/configs/flutter-engine.json b/configs/flutter-engine.json
index 2ab4838..05250ae 100644
--- a/configs/flutter-engine.json
+++ b/configs/flutter-engine.json
@@ -1,6 +1,6 @@
 {
     "id": "flutter-engine",
-    "load": false,
+    "load": true,
     "supported_archs": [
         "x86_64",
         "arm64"
@@ -99,4 +99,4 @@
             }
         ]
     }
-}
\ No newline at end of file
+}

Note sure (if I'm missing something) why you changed flutter-engine.json and agl-qemu-master.json load too false. 
as we have --plex (Platform Load Excludes) option.

I know your busy, and this isn't a priority but just when you have time can you: - 
1) put these 2 loads back to true "or perhaps" change/include a --plinc  (Platform Load Includes) option
2) port jw/impeller_gl "Add missing packages" commit to main i.e. the libsecret stuff
3) Your workspace-automation actions failing, ubuntu cancelled because macos12 failed, macos12 failed because ModuleNotFoundError: No module named 'yaml'. Be great if you can resolve as these are great to follow when debugging own issues.

**Comment by bernardcraddock** [comment]
git diff configs/desktop-homescreen.json
diff --git a/configs/desktop-homescreen.json b/configs/desktop-homescreen.json
index 88ba0dc..d6977c9 100644
--- a/configs/desktop-homescreen.json
+++ b/configs/desktop-homescreen.json
@@ -13,7 +13,7 @@
   "env": {
     "HOMESCREEN_SRC_DIR": "${FLUTTER_WORKSPACE}/app/ivi-homescreen",
     "HOMESCREEN_BUILD_DIR": "${FLUTTER_WORKSPACE}/app/ivi-homescreen/build",
-    "HOMESCREEN_CMAKE_ARGS": "-DCMAKE_BUILD_TYPE=Debug -DENABLE_DLT=OFF",
+    "HOMESCREEN_CMAKE_ARGS": "-DCMAKE_BUILD_TYPE=Debug -DENABLE_DLT=OFF -DBUILD_PLUGIN_SECURE_STORAGE=ON",
     "HOMESCREEN_EXE": "${HOMESCREEN_BUILD_DIR}/shell/homescreen --j=${PLATFORM_ID_DIR_RELATIVE}/default_config.json --b=${PLATFORM_ID_DIR_RELATIVE}",
     "PING_CMD": "loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type",
     "CREATE_BUNDLE_FOLDER": "mkdir -p ${PLATFORM_ID_DIR_RELATIVE}/data",
@@ -43,7 +43,7 @@
             "sudo apt install lsb-release wget software-properties-common gnupg apt-file",
             "sudo apt-file update",
             "sudo apt install -y libwayland-dev wayland-protocols mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev mesa-utils libxkbcommon-dev ninja-build",
-            "sudo apt install -y build-essential libvulkan-dev vulkan-tools vulkan-validationlayers vulkan-utils libtool",
+            "sudo apt install -y build-essential libvulkan-dev vulkan-tools vulkan-validationlayers vulkan-utils libtool libsecret-1-dev libcurl4-openssl-dev",
             "sudo apt autoremove -y",
             "sudo apt clean -y",
             "cmake --version",
@@ -54,7 +54,7 @@
           "cmds": [
             "sudo dnf -y update",
             "sudo dnf -y upgrade",
-            "sudo dnf -y install wayland-devel wayland-protocols-devel libxkbcommon-devel cmake ninja-build mesa-dri-drivers mesa-filesystem mesa-libEGL-devel mesa-libGL-devel mesa-libGLU-devel mesa-libgbm-devel mesa-libglapi mesa-libxatracker mesa-vulkan-drivers vulkan-tools libunwind-devel gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-plugins-bad-free-devel gstreamer1-plugins-bad-free-extras gstreamer1-plugins-base-tools gstreamer1-plugins-good gstreamer1-plugins-good-extras gstreamer1-plugins-ugly-free libtool",
+            "sudo dnf -y install wayland-devel wayland-protocols-devel libxkbcommon-devel cmake ninja-build mesa-dri-drivers mesa-filesystem mesa-libEGL-devel mesa-libGL-devel mesa-libGLU-devel mesa-libgbm-devel mesa-libglapi mesa-libxatracker mesa-vulkan-drivers vulkan-tools libunwind-devel gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-plugins-bad-free-devel gstreamer1-plugins-bad-free-extras gstreamer1-plugins-base-tools gstreamer1-plugins-good gstreamer1-plugins-good-extras gstreamer1-plugins-ugly-free libtool libsecret-devel libcurl-devel",
             "sudo dnf -y autoremove",
             "cmake --version",
             "dnf provides cmake"
@@ -89,4 +89,4 @@
     "forwardPortSuccessRegex": null,
     "screenshot": null
   }
-}
\ No newline at end of file
+}

**Comment by jwinarske** [comment]
I'm thinking this is no longer an issue.  Feel free to open another issue.  The notification was lost in all the flutter org git messages, sorry!
