### ISSUE TITLE
workspace-automation failing on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by bernardcraddock** [meta-flutter/workspace-automation#5]
Hello,
Today i tried workspace-automation for the 1st time ( previously used meta-flutter/meta-flutter/tree/kirkstone/tools ) 
and it's failing for me using flutter_workspace.py --clean on Ubuntu 22.04.2 LTS 

As per following and attached (partial) flutter_workspace.log I encountered a couple of git cloning and make errors
and a bunch of compilation warnings.

Git cloning
------------
2 errors Git cloning of (PBR) Compositor Surface 3rd parties TinyGLTF and  KTX-Software

1) Cloning into '/home/parallels/Documents/GitHub/workspace-automation/app/comp_surf_pbr/third_party/tinygltf'...
git-lfs filter-process: 1: git-lfs: not found
fatal: the remote end hung up unexpectedly

2)  fatal: Unable to checkout '48b455cc997a446c42442e077e7f324a59c79544' in submodule path 'third_party/KTX-Software'

Making IVI Home screen  and target flutter-auto
------------------------------------------------

CMake Error at third_party/KTX-Software/CMakeLists.txt:864 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.
>> true - this directory does not exist

CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindVulkan.cmake:129 (find_package_handle_standard_args)
  CMakeLists.txt:59 (find_package)
 >> Not really sure what this means ,  3rd party vulkan directory does exits within 
workspace-automation/app/comp_surf_pbr/third_party/vulkan does exist and it just  contains a bunch of .h headers files. 

All other functionality within flutter_workspace including download and setup of flutter, engine artefacts, platform 
agl-qemu-octopus  seemed to work fine. 
I'm not sure if the build failed because of git clone errors or if something else is wrong/missing so appreciate your feedback

regards

[flutter_workspace.log](https://github.com/meta-flutter/workspace-automation/files/11570692/flutter_workspace.log)
[CMakeOutput.log](https://github.com/meta-flutter/workspace-automation/files/11570694/CMakeOutput.log)

**Comment by bernardcraddock** [comment]
Hello @jwinarske 

I installed the following on my Ubuntu VM and flutter workspace build completed
you may wish to update  flutter_workspace.py to include these for other guys like me.

Git LFS - sudo apt install git-lfs
vulkan.  - sudo apt install libvulkan-dev vulkan-tools vulkan-validationlayers vulkan-utils
libtool   - sudo apt install libtool

I could then safely run desktop-auto against several of the apps and will test against QEMU later , and Its good you included both master and stable octopus 

Couple of questions
1.  Is it fine for me to configure --flutter-version=3.7.x or even 3.10.1
2. Can you include Pumped PED AGL branch  https://github.com/bernardpumped/ped/tree/agl as one of thee apps

thank you and  best regards

**Comment by jwinarske** [comment]
Hi @bernardcraddock Updates here:  https://github.com/meta-flutter/workspace-automation/pull/7

You need to match the Flutter version against what is on the target image, unless you are focusing on desktop-auto.  Then you can change it to whatever you like; by design.
