### ISSUE TITLE
--flutter-version=3.10.x fails FileNotFoundError

### ISSUE THREAD

**Issue by bernardcraddock** [meta-flutter/workspace-automation#8]
@jwinarske 

Not sure if this issue is your's, Google or something else but every patch release of flutter 3.10.x I've tried fails with  FileNotFoundError, whilst patch release of  3.3.x  and 3.7.x i tried all downloaded respective linux-x64-embedder.zip just fine and completes the build successfully.

/flutter_workspace.py --clean --flutter-version=3.10.3 fails
    Engine Version: 2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d
    Working Directory: /home/parallels/Documents/GitHub/workspace-automation/.config/flutter_workspace/flutter-engine
    *********************************
    ** Downloading Engine artifact **
    *********************************
    ** Downloading linux-x64-embedder.zip via https://storage.googleapis.com/flutter_infra_release/flutter/2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d/linux-x64/linux-x64-embedder
    **************************
    ** Download Status: 404 **
    **************************
    ***********************************************
    ** Failed to download linux-x64-embedder.zip **
    ***********************************************
    Traceback (most recent call last):
      File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 2465, in <module>
        main()
      File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 282, in main
        get_flutter_engine_runtime(clean_workspace)
      File "/home/parallels/Documents/GitHub/workspace-automation/./flutter_workspace.py", line 1246, in get_flutter_engine_runtime
        with zipfile.ZipFile(archive_file, "r") as zip_ref:
      File "/usr/lib/python3.10/zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/parallels/Documents/GitHub/workspace-automation/.config/flutter_workspace/flutter-engine/2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d/linux-x64-embedder.zip'

**Comment by jwinarske** [comment]
3.10.5 is now supported.  The problem is that Google seems to have stopped archiving engine builds.  I added flutter-engine.json which will build the engine locally, opposed to pulling from Google storage.

**Comment by bernardcraddock** [comment]
thankyou



Bernard Craddock
Co-founder Pumped Fuel
www.pumpedfuel.com
L2, 11 York Street Sydney 2000
